CREATE TABLE "CUSTOMER"(
  id INTEGER NOT NULL,
  name TEXT,
  nationality TEXT,
  clearance INTEGER,
  phone_number TEXT,
  email TEXT,
  login TEXT,
  password TEXT,
  address TEXT,
  deleted_flag INTEGER,
  PRIMARY KEY(id)
);

CREATE TABLE "BRANCH"(
  id INTEGER NOT NULL,
  name TEXT,
  address TEXT,
  "DEPARTMENT_id" INTEGER NOT NULL,
  clients INTEGER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT "DEPARTMENT_BRANCH"
    FOREIGN KEY ("DEPARTMENT_id") REFERENCES "DEPARTMENT" (id),
  CONSTRAINT "CUSTOMER_BRANCH" FOREIGN KEY (clients) REFERENCES "CUSTOMER" (id)
);

CREATE TABLE "LOAN"(
  id INTEGER NOT NULL,
  initial_amount INTEGER,
  interest INTEGER,
  final_amount INTEGER,
  start_time INTEGER,
  end_time INTEGER,
  PRIMARY KEY(id)
);

CREATE TABLE "BANK"(
  id INTEGER NOT NULL,
  address TEXT,
  scale TEXT,
  "BRANCH_id" INTEGER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT "BRANCH_BANK" FOREIGN KEY ("BRANCH_id") REFERENCES "BRANCH" (id)
);

CREATE TABLE "DEPARTMENT"(
  id INTEGER NOT NULL,
  name TEXT,
  employees INTEGER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT "CUSTOMER_DEPARTMENT"
    FOREIGN KEY (employees) REFERENCES "CUSTOMER" (id)
);

CREATE TABLE "TRANSACTION"(
  id INTEGER NOT NULL,
  amount INTEGER,
  date INTEGER,
  receiver_id INTEGER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT "CUSTOMER_TRANSACTION"
    FOREIGN KEY (receiver_id) REFERENCES "CUSTOMER" (id)
);

CREATE TABLE "BUSINESS ACCOUNT"(
  id INTEGER NOT NULL,
  balance INTEGER,
  interest INTEGER,
  name TEXT,
  "LOAN_id" INTEGER NOT NULL,
  "TRANSACTION_id" INTEGER NOT NULL,
  owner INTEGER NOT NULL,
  employees INTEGER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT "LOAN_BUSINESS ACCOUNT"
    FOREIGN KEY ("LOAN_id") REFERENCES "LOAN" (id),
  CONSTRAINT "TRANSACTION_BUSINESS ACCOUNT"
    FOREIGN KEY ("TRANSACTION_id") REFERENCES "TRANSACTION" (id),
  CONSTRAINT "CUSTOMER_BUSINESS ACCOUNT"
    FOREIGN KEY (owner) REFERENCES "CUSTOMER" (id),
  CONSTRAINT "CUSTOMER_BUSINESS ACCOUNT"
    FOREIGN KEY (employees) REFERENCES "CUSTOMER" (id)
);

CREATE TABLE "PRIVATE ACCOUNT"(
  id INTEGER NOT NULL,
  balance INTEGER,
  interest INTEGER,
  "TRANSACTION_id" INTEGER NOT NULL,
  "LOAN_id" INTEGER NOT NULL,
  "CUSTOMER_id" INTEGER NOT NULL,
  PRIMARY KEY(id),
  CONSTRAINT "TRANSACTION_PRIVATE ACCOUNT"
    FOREIGN KEY ("TRANSACTION_id") REFERENCES "TRANSACTION" (id),
  CONSTRAINT "LOAN_PRIVATE ACCOUNT" FOREIGN KEY ("LOAN_id") REFERENCES "LOAN" (id),
  CONSTRAINT "CUSTOMER_PRIVATE ACCOUNT"
    FOREIGN KEY ("CUSTOMER_id") REFERENCES "CUSTOMER" (id)
);
